services:
  mysql:
    image: mysql:8.0
    container_name: bonos_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bonos_db
      MYSQL_USER: bonos_user
      MYSQL_PASSWORD: bonos_pass

    #ports:
    #  - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 10

    networks:
      - bonos-net

  backend:
    build: ./backend
    container_name: bonos_api
    restart: always

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/bonos_db
      BANXICO_TOKEN: ${BANXICO_TOKEN}
    networks:
      - bonos-net

  frontend:
    build:
      context: ./bono-ui
    container_name: next_bono-ui
    ports:
      - "3000:3000"
    restart: always

    depends_on:
      - backend

    networks:
      - bonos-net

networks:
  bonos-net:
    driver: bridge

volumes:
  mysql_data:
