# Puerto
server.port=8080

# MySQL (Docker)
spring.datasource.url=jdbc:mysql://mysql:3306/bonos_db
spring.datasource.username=bonos_user
spring.datasource.password=bonos_pass
jwt.secret=mysupersecretkeymysupersecretkey123456
jwt.expiration=86400000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=backend

banxico.token=${BANXICO_TOKEN}
