# Puerto
server.port=8080

# MySQL (Docker)
spring.datasource.url=jdbc:mysql://mysql:3306/bonos_db
spring.datasource.username=root
spring.datasource.password=root

# JWT
jwt.secret=CAMBIA_ESTO_POR_UN_SECRET_LARGO_Y_SEGURO
jwt.expiration=86400000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.application.name=backend

# Permitir que los mensajes de las excepciones se incluyan en el JSON de respuesta
server.error.include-message=always
